name: Deploy

on:
  push:
    branches: [master]

permissions:
  contents: write   

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./MyWPFApp

    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0      
        
    - name: Get Version from Project File
      id: get-version
      shell: bash
      run: echo "version=$(grep -oE '<Version>[^<]+' MyWPFApp.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.x

    - name: Publish Selfcontained
      run: dotnet publish -c Release --self-contained -r win-x64 -o .\publish-win-x64

    - name: Dotnet Clean
      run: dotnet clean

    - name: Publish .NET10
      run: dotnet publish -c Release --no-self-contained -r win-x64 -o .\publish-win-x64-net10

    - name: Create Release Notes
      uses: softprops/action-gh-release@v3
      with:
        name: "MyWPFApp ${{ steps.get-version.outputs.version }}"
        tag_name: ${{ steps.get-version.outputs.version }}
        generate_release_notes: true
        draft: true

    - name: Create Velopack Release
      run: |
        dotnet tool install -g vpk
        vpk download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }} --channel win-x64
        vpk download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }} --channel win-x64-net10
        vpk pack --channel win-x64 -u MyWPFApp -v ${{ steps.get-version.outputs.version }} -p .\publish-win-x64 --packTitle "My WPF App" --mainExe MyWPFApp.exe
        vpk pack --channel win-x64-net10 -u MyWPFApp -v ${{ steps.get-version.outputs.version }} -p .\publish-win-x64-net10 --packTitle "My WPF App" --mainExe MyWPFApp.exe
        vpk upload github --repoUrl https://github.com/${{ github.repository }} --channel win-x64 --merge --releaseName "MyWPFApp ${{ steps.get-version.outputs.version }}" --tag ${{ steps.get-version.outputs.version }} --token ${{ secrets.GITHUB_TOKEN }}
        vpk upload github --repoUrl https://github.com/${{ github.repository }} --channel win-x64-net10 --merge --publish --releaseName "MyWPFApp ${{ steps.get-version.outputs.version }}" --tag ${{ steps.get-version.outputs.version }} --token ${{ secrets.GITHUB_TOKEN }}
